### ISSUE TITLE
Ошибка при создании таблицы

### ISSUE THREAD

**Issue by mnoskov** [webber12/CommerceDiscounts#1]
#1067 - Invalid default value for 'date_create'.
Наверное нужно тип указывать timestamp, а не datetime, чтобы использовать CURRENT_TIMESTAMP.

**Comment by webber12** [comment]
Похоже, зависит от версии MySQL, у меня на OpenServer MySql 5.6.41 работает вроде - попробовал еще раз только что. Таблица создалась - https://yadi.sk/i/v4bEsI5ama1upg 
https://yadi.sk/i/T3flrpz6aKys-g
И дефолтные пустые записи создаются как и задумано - https://yadi.sk/i/3CDChpozg9-Ufw . В общем, надо посмотреть, как так сделать, чтобы туда писало текущее время, а в две другие даты NULL :)

**Comment by mnoskov** [comment]
У меня MySQL 5.5.55 на линуксе

**Comment by webber12** [comment]
5.5 вроде умерла окончательно в декабре 2018 https://www.fromdual.com/support-for-mysql-from-oracle . Есть ли возможность глянуть на 5.6, 5.7 и т.п.? Возможно, не стоит 5.5 и ворошить уже, если выше работает :)

**Comment by mnoskov** [comment]
5.6.39 - создается без ошибок
